### ISSUE TITLE
libNNPOpsPyTorch.so: undefined symbol: _ZN3c1012OptionalTypeC1ESt10shared_ptrINS_4TypeEE

### ISSUE THREAD

**Issue by rvkrishnan30** [openmm/NNPOps#54]
Hi, 

I installed the NNPOps package from the conda-forge channel with the command:
`conda install -c conda-forge nnpops`

The installation finished without any issues but when I try to import the required modules, I get the following error message

>>> import torch 
>>> import torchani
>>> **from NNPOps.SpeciesConverter import TorchANISpeciesConverter**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/__init__.py", line 1, in <module>
    from NNPOps.OptimizedTorchANI import OptimizedTorchANI
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/OptimizedTorchANI.py", line 28, in <module>
    from NNPOps.BatchedNN import TorchANIBatchedNN
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/BatchedNN.py", line 31, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), 'libNNPOpsPyTorch.so'))
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/libNNPOpsPyTorch.so: undefined symbol: _ZN3c1012OptionalTypeC1ESt10shared_ptrINS_4TypeEE**

I am not sure how to fix this error and any help would be highly appreciated. Happy to provide any additional information if needed. 

I am working with `Python 3.9.12` on a Debian OS machine.

**Comment by peastman** [comment]
The demangled version of the symbol it's looking for is `c10::OptionalType::OptionalType(std::shared_ptr<c10::Type>)`.  That's part of the PyTorch C++ API.  How did you install PyTorch?  Make sure its libraries are in your library path.

**Comment by peastman** [comment]
The last paragraph of https://github.com/openmm/openmm-torch/issues/67 may be relevant.  It's talking about Macs, but the same probably applies to Linux.  Try adding the PyTorch lib directory to `LD_LIBRARY_PATH`.

**Comment by rvkrishnan30** [comment]
@peastman, regarding the PyTorch installation: the nnpops installation via conda (`conda install -c conda-forge nnpops`) also installed `pytorch-1.11.0`. 

As you suggested in https://github.com/openmm/openmm-torch/issues/67, I noticed that the PyTorch libraries were in `site-packages/torch/lib` and added it to the `LD_LIBRARY_PATH` in the terminal (`export LD_LIBRARY_PATH="/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/torch/lib:$LD_LIBRARY_PATH"
`)

Unfortunately, this did not help in my case and I still get the same message. 

Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchani
>>> from NNPOps.SpeciesConverter import TorchANISpeciesConverter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/__init__.py", line 1, in <module>
    from NNPOps.OptimizedTorchANI import OptimizedTorchANI
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/OptimizedTorchANI.py", line 28, in <module>
    from NNPOps.BatchedNN import TorchANIBatchedNN
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/BatchedNN.py", line 31, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), 'libNNPOpsPyTorch.so'))
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/venkat/miniconda3/envs/py39/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/venkat/miniconda3/envs/py39/lib/python3.9/site-packages/NNPOps/libNNPOpsPyTorch.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo


Not sure if I am missing something trivial here.

**Comment by raimis** [comment]
Let me check. It seems something get broken with the dependencies.

**Comment by raimis** [comment]
Related: https://github.com/torchmd/torchmd-net/issues/85

**Comment by raimis** [comment]
@rvkrishnan30 I cannot reproduce the issue.

I create a clean enviroment:
```
conda create -n tmp-nnpops -c conda-forge nnpops
```
and I don't get the import error:
```
conda acitvate tmp-nnpops
python -c "from NNPOps.SpeciesConverter import TorchANISpeciesConverter"
```

List of packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8        py39hf3d152e_2    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39hd97740a_1    conda-forge
cudatoolkit               11.6.0              habf752d_10    conda-forge
cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
future                    0.18.2           py39hf3d152e_5    conda-forge
h5py                      3.6.0           nompi_py39h7e08c79_100    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hf3d152e_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
intel-openmp              2022.0.1          h06a4308_3633  
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lark-parser               0.12.0             pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0            14_linux64_mkl    conda-forge
libcblas                  3.9.0            14_linux64_mkl    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0            14_linux64_mkl    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libprotobuf               3.19.4               h780b84a_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
magma                     2.5.4                h6103c52_2    conda-forge
mkl                       2022.0.1           h06a4308_117  
nccl                      2.12.10.1            h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.10.2               h4bd325d_1    conda-forge
nnpops                    0.2             cuda112py39h74ce309_1    conda-forge
numpy                     1.22.3           py39hc58783e_2    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.1               pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
python                    3.9.12          h9a8a25e_1_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.2          cuda112py39h4de5995_1    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
setuptools                59.5.0           py39hf3d152e_0    conda-forge
setuptools-scm            6.3.2              pyhd8ed1ab_0    conda-forge
setuptools_scm            6.3.2                hd8ed1ab_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
torchani                  2.2.2           cuda112py39hbfe6faf_3    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

**Comment by rvkrishnan30** [comment]
@peastman, the default conda installation of NNPOPs installed `pytorch-1.11.0` on my machine while I noticed the `environment.yml` (https://github.com/openmm/NNPOps/blob/master/environment.yml) states `pytorch-gpu 1.10.0`. So, to test if it could be the version difference that's causing this issue, I was trying to install the exact packages as in the yml (`conda env create -n nnpops -f environment.yml`) and on another occasion, to compile from source but ran into some other issues with my local machine and had to halt till that got sorted at my end. Will retry building from source later and see. 

@raimis, to see if I could reproduce the error again now with a clean environment, I tried
`conda create -n tmp-nnpops -c conda-forge nnpops`
`conda activate tmp-nnpops`
`conda install -c conda-forge mdtraj`

and this time I did not get any errors. All the imports (`import mdtraj, import torch, import torchani, from NNPOps import OptimizedTorchANI`) worked fine. Even better, it seems to be with python 3.10 and pytorch 1.11 (below is the list of packages).  Has the update been applied to the conda package to automatically work with new builds of pytorch/torchani? 

Still not sure why I encountered the undefined symbol error before and that too on 2 separate machine (WSL and debian) and with multiple fresh installs of nnpops package with conda. But yes, a complete clean environment solved the issue and perhaps some pre-installed package/dependency on my machine was interfering with nnpops. Would be useful to find out what exactly was the reason. 

Also, the other linked issues (https://github.com/openmm/openmm-torch/issues/67; https://github.com/rusty1s/pytorch_cluster/issues/100; https://github.com/torchmd/torchmd-net/issues/85; https://github.com/conda-forge/nnpops-feedstock/pull/3 ) were all very helpful reads. Thank you for your help. Really appreciate that.


```
List of packages:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h83bc5f7_2    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8       py310hff52083_2    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2          py310h597c629_1    conda-forge
cudatoolkit               11.6.0              habf752d_10    conda-forge
cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lark-parser               0.12.0             pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0            14_linux64_mkl    conda-forge
libcblas                  3.9.0            14_linux64_mkl    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
liblapack                 3.9.0            14_linux64_mkl    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libprotobuf               3.20.1               h6239696_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
llvm-openmp               14.0.3               he0ac6c6_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
magma                     2.5.4                h6103c52_2    conda-forge
mdtraj                    1.9.7           py310hd8d60c7_1    conda-forge
mkl                       2022.0.1           h8d4b97c_803    conda-forge
nccl                      2.12.12.1            h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
nnpops                    0.2             cuda112py310h85a0d14_3    conda-forge
numexpr                   2.8.0           mkl_py310h0afd4a5_2    conda-forge
numpy                     1.22.3          py310h4ef5377_2    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2           py310h769672d_1    conda-forge
pip                       22.1               pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310hff52083_5    conda-forge
pytables                  3.7.0           py310hf5df6ce_0    conda-forge
**python                    3.10.4          h9a8a25e_0_cpython    conda-forge**
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
**pytorch                   1.11.0          cuda112py310h51fe464_1    conda-forge**
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scipy                     1.8.0           py310hea5193d_1    conda-forge
setuptools                62.2.0          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
snappy                    1.1.9                hbd366e4_0    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
torchani                  2.2                pyh9f0ad1d_0    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge

```

**Comment by raimis** [comment]
@rvkrishnan30 a few days ago `conda-forge` has rebuild the packages for Python 3.10 (https://github.com/conda-forge/nnpops-feedstock/pull/5) and PyTorch 1.11 (https://github.com/conda-forge/nnpops-feedstock/pull/3). I guess, this implicitly fixed the issue.

Regarding the enviroment file (https://github.com/openmm/NNPOps/blob/master/environment.yml), eventually I'll update it to match `conda-forge`.

**Comment by rvkrishnan30** [comment]
@raimis, that's good to know. Thank you very much.
