### ISSUE TITLE
Conda install not working

### ISSUE THREAD

**Issue by davkovacs** [openmm/NNPOps#60]
I cannot install the package from conda:

```sh
conda install -c conda-forge nnpops
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nnpops -> __glibc[version='>=2.17,>=2.17,<3.0.a0']

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Does anyone know what might be the cause of this?

**Comment by raimis** [comment]
Either you have very old Linux distro or conda doesn't detect correctly the glibc version.

Could you share the output of:
```
conda info
```

**Comment by davkovacs** [comment]
```sh
conda info

     active environment : MACE
    active env location : /home/dpk25/.conda/envs/MACE
            shell level : 1
       user config file : /home/dpk25/.condarc
 populated config files : /home/dpk25/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/miniconda3-4.5.4-hivczbzklvoccmuifapprxz7humnmn5c  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/miniconda3-4.5.4-hivczbzklvoccmuifapprxz7humnmn5c/pkgs
                          /home/dpk25/.conda/pkgs
       envs directories : /home/dpk25/.conda/envs
                          /usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/miniconda3-4.5.4-hivczbzklvoccmuifapprxz7humnmn5c/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.8 Linux/3.10.0-1160.66.1.el7.x86_64 scientific/7.9 glibc/2.17
                UID:GID : 17364:17369
             netrc file : None
           offline mode : False
```

**Comment by raimis** [comment]
Your conda is too old and don't support the virtual packages (like `__glibc`). Update to the latest conda.

**Comment by davkovacs** [comment]
Thank you, I actually realized that the conda release is not fit for me as I need the new neighborlist kernel. 

So I compiled that from source, but am still encountering a problem I don't seem to be able to solve. Have you seen this before by any chance? (I actually only compiled the neighbors subdirectory of the package, as I don't need any of the ANI / SCHNet code)

```
>>> neighbors, distances = getNeighborPairs(positions, cutoff=cutoff, max_num_neighbors=100)
Traceback (most recent call last):
  File "/home/dpk25/.conda/envs/MACE/lib/python3.10/site-packages/torch/_ops.py", line 203, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator neighbors::getNeighborPairs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpk25/.conda/envs/MACE/lib/python3.10/site-packages/NNPOps/neighbors/getNeighborPairs.py", line 82, in getNeighborPairs
    return ops.neighbors.getNeighborPairs(positions, cutoff, max_num_neighbors)
  File "/home/dpk25/.conda/envs/MACE/lib/python3.10/site-packages/torch/_ops.py", line 207, in __getattr__
    raise AttributeError(f"'_OpNamespace' object has no attribute '{op_name}'") from e
AttributeError: '_OpNamespace' object has no attribute 'getNeighborPairs'
```

**Comment by raimis** [comment]
It seems that PyTorch cannot find your compiled library.

**Comment by davkovacs** [comment]
and what might be the cause of that? Any recommendations how I could debug?

**Comment by peastman** [comment]
Possibly you just need to add the directory to `LD_LIBRARY_PATH`?

**Comment by peastman** [comment]
The folder you want to add is wherever you had it install the libraries to.
